version: '3'
services:
  db:
    image: postgres:15.5
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d/ # 恐らく使わない
    environment:
      POSTGRES_USER: 'test_user'
      POSTGRES_PASSWORD: 'test_pass'
      POSTGRES_DB: 'test_db'
